### ISSUE TITLE
Dodać możliwość wchodzenia po chodnikach

### ISSUE THREAD

**Issue by Gekonisko** [AGH-Code-Industry/student-trainer#12]
**Definition of Done**
- [x] Dodać do obiektów schody komponent mesh collider
- [x] Zmienić komponent rigidbody u gracza (ustawić drag = 0, useGravity = true)
- [x] Zmienić komponent Box Collider u gracza (isTrigger = true)
- [ ] Upewnić się czy wszytko działa poprawnie oraz dowiedzieć się czy da się to ulepszyć

**Comment by Janosik8** [comment]
skrypt 'custom actions' wywalał mi błędy więc go usunąłem i wykonałem to zadanie.
